<a href="https://colab.research.google.com/github/VarunRathod74/PESUIO_assign/blob/main/nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.13.0'

In [4]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [6]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [9]:
print(X)

[[ 19   4]
 [ 35   5]
 [ 26  26]
 [ 27  39]
 [ 19  57]
 [ 27  40]
 [ 27  65]
 [ 32 116]
 [ 25  17]
 [ 35  47]
 [ 26  61]
 [ 26  35]
 [ 20  67]
 [ 32   3]
 [ 18  63]
 [ 29  61]
 [ 47   9]
 [ 45  10]
 [ 46  12]
 [ 48  13]
 [ 45   7]
 [ 47  32]
 [ 48  24]
 [ 45   7]
 [ 46   8]
 [ 47   5]
 [ 49  12]
 [ 47  14]
 [ 29  26]
 [ 31   3]
 [ 31  55]
 [ 27 105]
 [ 21   1]
 [ 28  27]
 [ 27  71]
 [ 35  11]
 [ 33  12]
 [ 30  32]
 [ 26  53]
 [ 27  15]
 [ 27   2]
 [ 33  34]
 [ 35  85]
 [ 30   0]
 [ 28  65]
 [ 23   5]
 [ 25  60]
 [ 27  37]
 [ 30 104]
 [ 31  70]
 [ 24  16]
 [ 18  27]
 [ 29  64]
 [ 35   8]
 [ 27  40]
 [ 24  38]
 [ 23  31]
 [ 28  60]
 [ 22   3]
 [ 32  91]
 [ 27   5]
 [ 25  68]
 [ 23  48]
 [ 32  94]
 [ 59  64]
 [ 24  40]
 [ 24   4]
 [ 23  63]
 [ 22  45]
 [ 31  49]
 [ 25  61]
 [ 24  11]
 [ 20   8]
 [ 33  87]
 [ 32   3]
 [ 34  86]
 [ 18  35]
 [ 22  11]
 [ 28  68]
 [ 26   2]
 [ 30  61]
 [ 39  25]
 [ 20  32]
 [ 35  69]
 [ 30  44]
 [ 31  92]
 [ 24  38]
 [ 28  66]
 [ 26  62]
 [ 35  33]
 [ 22  62]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
10/10 [==============================] - 2s 3ms/step - loss: 0.6540 - accuracy: 0.6750
Epoch 2/100
10/10 [==============================] - 0s 2ms/step - loss: 0.6375 - accuracy: 0.7375
Epoch 3/100
10/10 [==============================] - 0s 2ms/step - loss: 0.6224 - accuracy: 0.7437
Epoch 4/100
10/10 [==============================] - 0s 2ms/step - loss: 0.6084 - accuracy: 0.7531
Epoch 5/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5953 - accuracy: 0.7656
Epoch 6/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5832 - accuracy: 0.7656
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5725 - accuracy: 0.7688
Epoch 8/100
10/10 [==============================] - 0s 3ms/step - loss: 0.5615 - accuracy: 0.7719
Epoch 9/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5520 - accuracy: 0.7719
Epoch 10/100
10/10 [==============================] - 0s 2ms/step - loss: 0.5424 - accuracy: 0.7750
Epoch 11/

In [18]:
print(ann.predict(sc.transform([[20, 50000]])) > 1)

1/1 [==============================] - 0s 166ms/step
[[False]]


In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

3/3 [==============================] - 0s 3ms/step
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[54  4]
 [ 1 21]]


0.9375